# Generated by Django 3.2.3 on 2021-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('series', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('available', models.BooleanField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
